# Generated by Django 5.2.16 on 2026-08-11 17:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_stage_model'),
        ('students', '0002_guardianstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='academics.academicyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student')),
            ],
            options={
                'db_table': 'students_enrollment',
                'ordering': ['-enrollment_date', '-created_at'],
                'indexes': [models.Index(fields=['academic_year', 'section'], name='students_enr_year_section_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year'), name='students_enrollment_unique_student_year')],
            },
        ),
    ]
