# Generated by Django 5.2.16 on 2026-08-11 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_stage_model'),
        ('students', '0003_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('section_transfer', 'نقل بين الشعب')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='students.enrollment')),
                ('new_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_transfer_logs_to', to='academics.section')),
                ('old_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_transfer_logs_from', to='academics.section')),
            ],
            options={
                'db_table': 'students_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
