# Generated by Django 5.2.16 on 2026-08-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='usual_arrival_method',
            field=models.CharField(choices=[('school_bus', 'باص المدرسة'), ('guardian', 'ولي الأمر')], default='school_bus', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='usual_departure_method',
            field=models.CharField(choices=[('school_bus', 'باص المدرسة'), ('guardian', 'ولي الأمر')], default='school_bus', max_length=20),
        ),
    ]
