# Generated by Django 5.2.16 on 2026-08-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_enrollment_usual_arrival_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='usual_arrival_method',
            field=models.CharField(blank=True, choices=[('school_bus', 'باص المدرسة'), ('guardian', 'ولي الأمر')], default='school_bus', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='usual_departure_method',
            field=models.CharField(blank=True, choices=[('school_bus', 'باص المدرسة'), ('guardian', 'ولي الأمر')], default='school_bus', max_length=20, null=True),
        ),
    ]
