# Generated by Django 5.2.16 on 2026-09-11 18:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_enrollment_usual_arrival_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianstudent',
            name='relationship',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='StudentHealthProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_type', models.CharField(blank=True, default='', max_length=10)),
                ('chronic_diseases', models.TextField(blank=True, default='')),
                ('allergies', models.TextField(blank=True, default='')),
                ('permanent_medications', models.TextField(blank=True, default='')),
                ('special_health_needs', models.TextField(blank=True, default='')),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('health_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='students.student')),
            ],
            options={
                'db_table': 'students_student_health_profile',
            },
        ),
    ]
