# Generated by Django 5.2.16 on 2026-09-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_backfill_student_health_profiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name'], 'permissions': [('register_student', 'تسجيل طالب'), ('transfer_student', 'نقل طالب بين الشعب')]},
        ),
    ]
