# Generated by Django 5.2.16 on 2026-09-24 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_add_student_profile_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(max_length=64)),
                ('file_size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('validation_failed', 'Validation failed'), ('ready', 'Ready'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed')], default='pending', max_length=25)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('invalid_rows', models.IntegerField(default=0)),
                ('review_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('succeeded_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('batch_size', models.PositiveSmallIntegerField(default=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students_import_job',
            },
        ),
        migrations.CreateModel(
            name='StudentImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('normalized_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('review_required', 'Review required'), ('invalid', 'Invalid'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('validation_errors', models.JSONField(default=list)),
                ('attempt_count', models.IntegerField(default=0)),
                ('lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_rows', to='students.enrollment')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_import_rows', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='students.studentimportjob')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_rows', to='students.student')),
            ],
            options={
                'db_table': 'students_import_row',
            },
        ),
        migrations.AddConstraint(
            model_name='studentimportjob',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__gte', 0)), name='students_imp_job_file_size_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='studentimportjob',
            constraint=models.CheckConstraint(condition=models.Q(('total_rows__gte', 0)), name='students_imp_job_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='studentimportjob',
            constraint=models.CheckConstraint(condition=models.Q(('valid_rows__gte', 0)), name='students_imp_job_valid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='studentimportjob',
            constraint=models.CheckConstraint(condition=models.Q(('invalid_rows__gte', 0)), name='students_imp_job_invalid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='studentimportjob',
            constraint=models.CheckConstraint(condition=models.Q(('review_rows__gte', 0)), name='students_imp_job_review_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='studentimportjob',
            constraint=models.CheckConstraint(condition=models.Q(('processed_rows__gte', 0)), name='students_imp_job_processed_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='studentimportjob',
            constraint=models.CheckConstraint(condition=models.Q(('succeeded_rows__gte', 0)), name='students_imp_job_succeeded_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='studentimportjob',
            constraint=models.CheckConstraint(condition=models.Q(('failed_rows__gte', 0)), name='students_imp_job_failed_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='studentimportjob',
            constraint=models.CheckConstraint(condition=models.Q(('batch_size__gte', 1), ('batch_size__lte', 100)), name='students_imp_job_batch_size_range'),
        ),
        migrations.AddIndex(
            model_name='studentimportrow',
            index=models.Index(fields=['job', 'status', 'row_number'], name='stud_imp_job_status_row_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentimportrow',
            constraint=models.UniqueConstraint(fields=('job', 'row_number'), name='students_imp_row_unique_job_row'),
        ),
        migrations.AddConstraint(
            model_name='studentimportrow',
            constraint=models.CheckConstraint(condition=models.Q(('row_number__gte', 1)), name='students_imp_row_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='studentimportrow',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__gte', 0)), name='students_imp_row_attempts_nonnegative'),
        ),
    ]
