# Generated by Django 5.2.16 on 2026-09-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_studentauditlog_placement_correction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentimportjob',
            options={'permissions': [('import_students', 'استيراد الطلاب')]},
        ),
    ]
