# Generated by Django 5.2.16 on 2026-08-19 18:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_remove_stage_model'),
        ('students', '0006_alter_enrollment_usual_arrival_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeTuitionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_tuition_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuition_plans', to='academics.academicyear')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tuition_plans', to=settings.AUTH_USER_MODEL)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuition_plans', to='academics.gradelevel')),
            ],
            options={
                'db_table': 'finance_grade_tuition_plan',
            },
        ),
        migrations.CreateModel(
            name='StudentFinancialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_financial_accounts', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='financial_account', to='students.enrollment')),
                ('tuition_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_accounts', to='finance.gradetuitionplan')),
            ],
            options={
                'db_table': 'finance_student_account',
            },
        ),
        migrations.CreateModel(
            name='StudentDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(blank=True, choices=[('usd', 'دولار أمريكي'), ('syp', 'ليرة سورية')], default='', max_length=10)),
                ('exchange_rate_syp_per_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('equivalent_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_discounts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_discounts', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='finance.studentfinancialaccount')),
            ],
            options={
                'db_table': 'finance_student_discount',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('usd', 'دولار أمريكي'), ('syp', 'ليرة سورية')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('exchange_rate_syp_per_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('equivalent_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_payments', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.studentfinancialaccount')),
            ],
            options={
                'db_table': 'finance_payment',
            },
        ),
        migrations.AddConstraint(
            model_name='gradetuitionplan',
            constraint=models.UniqueConstraint(fields=('academic_year', 'grade_level'), name='fin_tuition_unique'),
        ),
        migrations.AddConstraint(
            model_name='gradetuitionplan',
            constraint=models.CheckConstraint(condition=models.Q(('base_tuition_usd__gt', 0)), name='fin_tuition_positive'),
        ),
        migrations.AddIndex(
            model_name='studentdiscount',
            index=models.Index(fields=['account', 'is_cancelled'], name='fin_disc_acc_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentdiscount',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='fin_disc_val_pos'),
        ),
        migrations.AddConstraint(
            model_name='studentdiscount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('currency', ''), ('discount_type', 'percentage'), ('equivalent_usd__isnull', True), ('exchange_rate_syp_per_usd__isnull', True), ('value__lte', 100)), models.Q(('currency', 'usd'), ('discount_type', 'fixed'), ('equivalent_usd', models.F('value')), ('exchange_rate_syp_per_usd__isnull', True)), models.Q(('currency', 'syp'), ('discount_type', 'fixed'), ('equivalent_usd__gt', 0), ('exchange_rate_syp_per_usd__gt', 0)), _connector='OR'), name='fin_disc_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='studentdiscount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('is_cancelled', False)), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('is_cancelled', True), models.Q(('cancellation_reason', ''), _negated=True)), _connector='OR'), name='fin_disc_cancel_valid'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['account', 'is_cancelled'], name='fin_pay_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at'], name='fin_pay_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fin_pay_amount_pos'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('equivalent_usd__gt', 0)), name='fin_pay_usd_pos'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('currency', 'usd'), ('equivalent_usd', models.F('amount')), ('exchange_rate_syp_per_usd__isnull', True)), models.Q(('currency', 'syp'), ('exchange_rate_syp_per_usd__gt', 0)), _connector='OR'), name='fin_pay_curr_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('is_cancelled', False)), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('is_cancelled', True), models.Q(('cancellation_reason', ''), _negated=True)), _connector='OR'), name='fin_pay_cancel_valid'),
        ),
    ]
