# Generated by Django 5.2.16 on 2026-09-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': [('cancel_payment', 'إلغاء دفعة')]},
        ),
        migrations.AlterModelOptions(
            name='studentdiscount',
            options={'permissions': [('cancel_discount', 'إلغاء حسم')]},
        ),
    ]
