# Generated by Django 5.2.16 on 2026-09-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_payment_options_alter_studentdiscount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
