# Generated by Django 5.2.16 on 2026-08-24 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_remove_stage_model'),
        ('students', '0006_alter_enrollment_usual_arrival_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('assessment_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
                ('grade_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.gradesubject')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_assessments', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.section')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.term')),
            ],
            options={
                'db_table': 'grades_assessment',
                'ordering': ['-assessment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='grades.assessment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_scores', to='students.enrollment')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_student_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grades_student_score',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['section', 'term', 'status'], name='gr_assess_sec_term_st_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='gr_assess_max_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('published_by__isnull', True), ('status', 'draft')), models.Q(('published_at__isnull', False), ('published_by__isnull', False), ('status', 'published')), _connector='OR'), name='gr_assess_publish_consistent'),
        ),
        migrations.AddConstraint(
            model_name='studentscore',
            constraint=models.UniqueConstraint(fields=('assessment', 'enrollment'), name='gr_score_unique_assess_enr'),
        ),
        migrations.AddConstraint(
            model_name='studentscore',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), ('score__gte', 0), _connector='OR'), name='gr_score_nonnegative'),
        ),
    ]
