# Generated by Django 5.2.16 on 2026-09-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_assessmentsection_scoreauditlog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-assessment_date', '-created_at'], 'permissions': [('publish_grades', 'نشر العلامات'), ('create_grade_wide_assessment', 'إنشاء تقييم لجميع شعب الصف')]},
        ),
    ]
