# Generated by Django 5.2.16 on 2026-08-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='user_role_required_unless_superuser',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_user_email_case_insensitive',
        ),
        migrations.AddField(
            model_name='user',
            name='temporary_password_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
