# Generated by Django 5.2.16 on 2026-09-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_backfill_guardian_national_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_user_permissions', 'إدارة صلاحيات المستخدمين'), ('reset_user_password', 'إعادة تعيين كلمة مرور المستخدم'), ('set_user_active', 'تغيير حالة حساب المستخدم')]},
        ),
    ]
