# Generated by Django 5.2.16 on 2026-09-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('school_admin', 'إدارة المدرسة'), ('secretariat', 'أمانة السر'), ('supervisor', 'الموجّه التربوي'), ('teacher', 'المعلّم'), ('accountant', 'المحاسب'), ('guardian', 'ولي الأمر'), ('tech_support', 'الدعم التقني')], default='', max_length=30),
        ),
    ]
