"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.
"""

from datetime import timedelta
from pathlib import Path

import environ

# =========================================================
# Base directory and environment variables
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)

environ.Env.read_env(
    BASE_DIR / ".env",
)


# =========================================================
# Core settings
# =========================================================

SECRET_KEY = env(
    "SECRET_KEY",
)

DEBUG = env(
    "DEBUG",
)

ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS",
    default=(
        [
            "127.0.0.1",
            "localhost",
        ]
        if DEBUG
        else []
    ),
)


# =========================================================
# Applications
# =========================================================

INSTALLED_APPS = [
    # Django applications
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party applications
    "rest_framework",
    "django_filters",
    "drf_spectacular",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    # Project applications
    "accounts",
    "academics" ,
    
]


# =========================================================
# Middleware
# =========================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # يجب أن يكون قبل CommonMiddleware.
    "corsheaders.middleware.CorsMiddleware",
    # مطلوب لـ Django Admin.
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # مطلوب لحماية Django Admin،
    # ونستخدم فحصه يدوياً مع JWT Cookies.
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# =========================================================
# URLs, Templates and WSGI
# =========================================================

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": ("django.template.backends.django." "DjangoTemplates"),
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                ("django.template.context_processors." "request"),
                ("django.contrib.auth.context_processors." "auth"),
                ("django.contrib.messages.context_processors." "messages"),
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# =========================================================
# Database
# =========================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env(
            "DB_NAME",
        ),
        "USER": env(
            "DB_USER",
        ),
        "PASSWORD": env(
            "DB_PASSWORD",
        ),
        "HOST": env(
            "DB_HOST",
            default="127.0.0.1",
        ),
        "PORT": env.int(
            "DB_PORT",
            default=5432,
        ),
        "OPTIONS": {
            "sslmode": env(
                "DB_SSLMODE",
                default="disable" if DEBUG else "require",
            ),
        },
    }
}


# =========================================================
# Password validation
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "MinimumLengthValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "CommonPasswordValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "NumericPasswordValidator"),
    },
]


# =========================================================
# Internationalization
# =========================================================

LANGUAGE_CODE = "ar"

TIME_ZONE = "Asia/Damascus"

USE_I18N = True

USE_TZ = True


# =========================================================
# Static files
# =========================================================

STATIC_URL = "/static/"


# =========================================================
# Models
# =========================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.User"


# =========================================================
# Django REST Framework
# =========================================================

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "accounts.exceptions.api_exception_handler",
    # مصادقة الـAPI تعتمد على JWT.
    #
    # هذا الكلاس المخصص:
    # - يقرأ Access Token من HttpOnly Cookie.
    # - يدعم Authorization Header للاختبار.
    # - يطبق CSRF عندما يأتي التوكن من Cookie.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.CookieJWTAuthentication",
    ],
    # جميع الـEndpoints محمية افتراضياً.
    # Login وCSRF وRefresh نضع لها AllowAny.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        "accounts.permissions.PasswordChangeGate",
    ],
    "DEFAULT_SCHEMA_CLASS": ("drf_spectacular.openapi.AutoSchema"),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": ("rest_framework.pagination.PageNumberPagination"),
    "PAGE_SIZE": 20,
    # معدل محاولات تسجيل الدخول.
    "DEFAULT_THROTTLE_RATES": {
        "web_login": "5/minute",
    },
}


# =========================================================
# Simple JWT
# =========================================================

SIMPLE_JWT = {
    # Access Token صالح لمدة 15 دقيقة.
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=15,
    ),
    # Refresh Token صالح لمدة 7 أيام.
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=7,
    ),
    # إصدار Refresh Token جديد عند كل Refresh.
    "ROTATE_REFRESH_TOKENS": True,
    # تعطيل Refresh Token القديم بعد تدويره.
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    # مفتاح مستقل لتوقيع JWT.
    "SIGNING_KEY": env(
        "JWT_SIGNING_KEY",
    ),
}


# =========================================================
# JWT HttpOnly Cookies
# =========================================================

# أسماء Cookies الخاصة بلوحة الويب.
JWT_ACCESS_COOKIE_NAME = env(
    "JWT_ACCESS_COOKIE_NAME",
    default="asas_web_access",
)

JWT_REFRESH_COOKIE_NAME = env(
    "JWT_REFRESH_COOKIE_NAME",
    default="asas_web_refresh",
)

# JavaScript لا يستطيع قراءة التوكنات.
JWT_COOKIE_HTTPONLY = True

# في الإنتاج تعمل Cookies على HTTPS فقط.
JWT_COOKIE_SECURE = not DEBUG

# مناسب إذا كان الويب والـAPI تحت نفس الموقع الأساسي:
# admin.asasschool.com
# api.asasschool.com
JWT_COOKIE_SAMESITE = env(
    "JWT_COOKIE_SAMESITE",
    default="Lax",
)

# نترك Cookie مرتبطة بدومين الـAPI الذي أنشأها.
JWT_COOKIE_DOMAIN = env(
    "JWT_COOKIE_DOMAIN",
    default=None,
)

# Access Cookie تستخدم مع جميع روابط الـAPI.
JWT_ACCESS_COOKIE_PATH = "/api/"

# Refresh Cookie لا تحتاج أن ترسل إلا لمسارات المصادقة.
JWT_REFRESH_COOKIE_PATH = "/api/v1/auth/web/"

# =========================================================
# Frontend and CORS
# =========================================================

FRONTEND_ORIGINS = env.list(
    "FRONTEND_ORIGINS",
    default=(
        [
            "http://127.0.0.1:5173",
            "http://localhost:5173",
        ]
        if DEBUG
        else []
    ),
)

# المصادر المسموح لها بالاتصال بالـAPI من المتصفح.
CORS_ALLOWED_ORIGINS = FRONTEND_ORIGINS

# ضروري لأن المتصفح سيرسل JWT Cookies مع الطلبات.
CORS_ALLOW_CREDENTIALS = True

# تطبيق CORS فقط على روابط الـAPI.
CORS_URLS_REGEX = r"^/api/.*$"


# =========================================================
# CSRF
# =========================================================

# يسمح لواجهة الويب بإرسال طلبات POST/PUT/PATCH/DELETE.
CSRF_TRUSTED_ORIGINS = FRONTEND_ORIGINS

CSRF_COOKIE_NAME = "asas_web_csrf"

# الواجهة تحصل على CSRF Token من Endpoint /csrf/
# لذلك لا تحتاج إلى قراءة Cookie نفسها عبر JavaScript.
CSRF_COOKIE_HTTPONLY = True

CSRF_COOKIE_SECURE = not DEBUG

CSRF_COOKIE_SAMESITE = env(
    "CSRF_COOKIE_SAMESITE",
    default="Lax",
)

CSRF_COOKIE_PATH = "/"

# نخزن CSRF Secret في Cookie وليس داخل Django Session.
CSRF_USE_SESSIONS = False


# =========================================================
# Django Admin Session security
# =========================================================

# هذه الإعدادات تخص Django Admin فقط،
# وليس تسجيل دخول Web Dashboard عبر JWT.

SESSION_COOKIE_NAME = "asas_admin_session"

SESSION_COOKIE_HTTPONLY = True

SESSION_COOKIE_SECURE = not DEBUG

SESSION_COOKIE_SAMESITE = "Lax"

SESSION_COOKIE_AGE = 8 * 60 * 60

SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# =========================================================
# API documentation
# =========================================================

SPECTACULAR_SETTINGS = {
    "TITLE": "Asas School Academic API",
    "DESCRIPTION": ("واجهة برمجة تطبيقات منصة مدرسة أساس الأكاديمية"),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
}
