# Generated by Django 5.2.16 on 2026-08-19 17:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0006_alter_enrollment_usual_arrival_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('complaint', 'شكوى'), ('suggestion', 'اقتراح'), ('inquiry', 'استفسار')], max_length=20)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('new', 'جديد'), ('answered', 'تمت الإجابة')], default='new', max_length=20)),
                ('school_response', models.TextField(blank=True, default='')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian', models.ForeignKey(limit_choices_to={'role': 'guardian'}, on_delete=django.db.models.deletion.PROTECT, related_name='school_requests', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_school_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_requests', to='students.student')),
            ],
            options={
                'db_table': 'school_requests_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='school_requ_status_2254db_idx'), models.Index(fields=['request_type', 'created_at'], name='school_requ_request_69610f_idx'), models.Index(fields=['guardian', 'created_at'], name='school_requ_guardia_a02d4d_idx')],
            },
        ),
    ]
