# Generated by Django 5.2.16 on 2026-09-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolrequest',
            options={'ordering': ['-created_at'], 'permissions': [('reply_to_request', 'الرد على طلب مدرسي')]},
        ),
    ]
