# Generated by Django 5.2.16 on 2026-08-17 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('homework_date', models.DateField()),
                ('due_date', models.DateField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_homeworks', to=settings.AUTH_USER_MODEL)),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homeworks', to='teaching.teacherassignment')),
            ],
            options={
                'ordering': ['-homework_date', '-created_at'],
                'indexes': [models.Index(fields=['teacher_assignment', 'homework_date'], name='homework_ho_teacher_f4cc69_idx'), models.Index(fields=['due_date'], name='homework_ho_due_dat_5d3fcb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('homework_date'))), name='homework_due_date_not_before_homework_date')],
            },
        ),
    ]
