# Generated by Django 5.2.16 on 2026-08-10 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_remove_stage_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='academics.gradesubject')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='academics.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teaching_teacher_assignment',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['teacher', 'start_date'], name='teaching_teacher_start_idx'), models.Index(fields=['grade_subject', 'section'], name='teaching_subject_section_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='teaching_assignment_end_not_before_start')],
            },
        ),
    ]
