# Generated by Django 5.2.16 on 2026-08-20 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_date', models.DateField()),
                ('request_reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('decision_reason', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_appointment_requests', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(limit_choices_to={'role': 'guardian'}, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointments_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'requested_date'], name='appt_status_date_idx'), models.Index(fields=['guardian', 'created_at'], name='appt_guardian_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('decided_by__isnull', True), ('decision_reason', ''), ('status', 'pending')), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False), ('status', 'approved'), models.Q(('decision_reason', ''), _negated=True)), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False), ('status', 'rejected'), models.Q(('decision_reason', ''), _negated=True)), _connector='OR'), name='appt_decision_state_valid')],
            },
        ),
    ]
