# Generated by Django 5.2.16 on 2026-08-31 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointmentrequest',
            name='appt_decision_state_valid',
        ),
        migrations.AddConstraint(
            model_name='appointmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('decided_by__isnull', True), ('decision_reason', ''), ('status', 'pending')), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False), ('decision_reason', ''), ('status', 'approved')), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False), ('status', 'rejected'), models.Q(('decision_reason', ''), _negated=True)), _connector='OR'), name='appt_decision_state_valid'),
        ),
    ]
