# Generated by Django 5.2.16 on 2026-09-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointmentrequest_appt_decision_state_valid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentrequest',
            options={'ordering': ['-created_at'], 'permissions': [('decide_appointment_request', 'اتخاذ قرار بشأن طلب موعد')]},
        ),
    ]
