# Generated by Django 5.2.16 on 2026-09-18 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointmentrequest_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointmentrequest',
            name='appt_decision_state_valid',
        ),
        migrations.RemoveIndex(
            model_name='appointmentrequest',
            name='appt_status_date_idx',
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='approval_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='requested_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='appointmentrequest',
            index=models.Index(fields=['status', 'requested_date', 'requested_time'], name='appt_status_datetime_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approval_note', ''), ('decided_at__isnull', True), ('decided_by__isnull', True), ('decision_reason', ''), ('status', 'pending')), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False), ('decision_reason', ''), ('status', 'approved')), models.Q(('approval_note', ''), ('decided_at__isnull', False), ('decided_by__isnull', False), ('status', 'rejected'), models.Q(('decision_reason', ''), _negated=True)), _connector='OR'), name='appt_decision_state_valid'),
        ),
    ]
