# Generated by Django 5.2.16 on 2026-08-08 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'فعال'), ('closed', 'مغلق')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academics_academic_year',
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='academics_year_end_after_start'), models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'active', 'closed'])), name='academics_year_valid_status'), models.UniqueConstraint(fields=('start_date', 'end_date'), name='academics_year_unique_dates'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('status',), name='academics_year_single_active')],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('kindergarten', 'الروضة'), ('primary', 'الابتدائية'), ('preparatory', 'الإعدادية'), ('secondary', 'الثانوية')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academics_stage',
                'constraints': [models.CheckConstraint(condition=models.Q(('code__in', ['kindergarten', 'primary', 'preparatory', 'secondary'])), name='academics_stage_valid_code'), models.UniqueConstraint(fields=('code',), name='academics_stage_unique_code')],
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_levels', to='academics.stage')),
            ],
            options={
                'db_table': 'academics_grade_level',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academics_subject',
                'constraints': [models.UniqueConstraint(fields=('name',), name='academics_subject_unique_name')],
            },
        ),
        migrations.CreateModel(
            name='GradeSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_subjects', to='academics.academicyear')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_subjects', to='academics.gradelevel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_subjects', to='academics.subject')),
            ],
            options={
                'db_table': 'academics_grade_subject',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'فعال'), ('closed', 'مغلق')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='academics.academicyear')),
            ],
            options={
                'db_table': 'academics_term',
                'ordering': ['-academic_year__start_date', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='academics.academicyear')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='academics.gradelevel')),
            ],
            options={
                'db_table': 'academics_section',
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'grade_level', 'name'), name='academics_section_unique_per_year_grade')],
            },
        ),
        migrations.AddConstraint(
            model_name='gradelevel',
            constraint=models.UniqueConstraint(fields=('stage', 'name'), name='academics_grade_unique_name_per_stage'),
        ),
        migrations.AddConstraint(
            model_name='gradesubject',
            constraint=models.UniqueConstraint(fields=('academic_year', 'grade_level', 'subject'), name='academics_grade_subject_unique_per_year'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.CheckConstraint(condition=models.Q(('number__in', [1, 2])), name='academics_term_valid_number'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='academics_term_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'active', 'closed'])), name='academics_term_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('academic_year', 'number'), name='academics_term_unique_number_per_year'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('academic_year',), name='academics_term_single_active_per_year'),
        ),
    ]
