# Generated by Django 5.2.16 on 2026-08-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='term',
            name='academics_term_valid_number',
        ),
        migrations.RemoveConstraint(
            model_name='term',
            name='academics_term_end_after_start',
        ),
        migrations.RemoveConstraint(
            model_name='term',
            name='academics_term_valid_status',
        ),
        migrations.RemoveConstraint(
            model_name='term',
            name='academics_term_unique_number_per_year',
        ),
        migrations.RemoveConstraint(
            model_name='term',
            name='academics_term_single_active_per_year',
        ),
        migrations.AlterField(
            model_name='term',
            name='number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'الأول'), (2, 'الثاني')]),
        ),
        migrations.AlterModelTable(
            name='term',
            table=None,
        ),
    ]
