# Generated by Django 5.2.16 on 2026-09-19 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_stage_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('all', 'كل المراحل'), ('selected_stages', 'مراحل محددة')], max_length=30)),
                ('supervisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_scope', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academics_supervisor_scope',
            },
        ),
        migrations.CreateModel(
            name='SupervisorScopeStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('kindergarten', 'الروضة'), ('primary', 'الابتدائية'), ('preparatory', 'الإعدادية'), ('secondary', 'الثانوية')], max_length=40)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='academics.supervisorscope')),
            ],
            options={
                'db_table': 'academics_supervisor_scope_stage',
            },
        ),
        migrations.AddConstraint(
            model_name='supervisorscope',
            constraint=models.CheckConstraint(condition=models.Q(('scope_type__in', ['all', 'selected_stages'])), name='academics_supervisor_scope_valid_type'),
        ),
        migrations.AddConstraint(
            model_name='supervisorscopestage',
            constraint=models.UniqueConstraint(fields=('scope', 'stage'), name='academics_supervisor_scope_unique_stage'),
        ),
        migrations.AddConstraint(
            model_name='supervisorscopestage',
            constraint=models.CheckConstraint(condition=models.Q(('stage__in', ['kindergarten', 'primary', 'preparatory', 'secondary'])), name='academics_supervisor_scope_valid_stage'),
        ),
    ]
