# Generated by Django 5.2.16 on 2026-09-01 20:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0006_alter_enrollment_usual_arrival_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('homework', 'الواجبات'), ('announcement', 'الإعلانات'), ('grades', 'العلامات'), ('attendance', 'الحضور'), ('behavior', 'السلوك'), ('finance', 'المالية'), ('school_request', 'الطلبات المدرسية'), ('appointment', 'المواعيد'), ('general', 'عام')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('resource_type', models.CharField(blank=True, default='', max_length=50)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('event_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(limit_choices_to={'role': 'guardian'}, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='students.student')),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'created_at'], name='notif_rec_created_idx'), models.Index(fields=['recipient', 'is_read', 'created_at'], name='notif_rec_read_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('event_key__isnull', False)), fields=('recipient', 'event_key'), name='notif_recipient_event_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('is_read', False), ('read_at__isnull', True)), models.Q(('is_read', True), ('read_at__isnull', False)), _connector='OR'), name='notif_read_state_valid'), models.CheckConstraint(condition=models.Q(models.Q(('resource_id__isnull', True), ('resource_type', '')), models.Q(models.Q(('resource_type', ''), _negated=True), ('resource_id__isnull', False)), _connector='OR'), name='notif_resource_pair_valid')],
            },
        ),
    ]
