# Generated by Django 5.2.16 on 2026-09-02 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installation_id', models.UUIDField(unique=True)),
                ('fcm_token', models.TextField()),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('device_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_push_device',
                'indexes': [models.Index(fields=['user', 'is_active', 'last_seen_at'], name='push_dev_user_active_seen_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fcm_token', ''), _negated=True), name='push_device_token_not_blank'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('fcm_token',), name='push_device_active_token_uniq')],
            },
        ),
    ]
