# Generated by Django 5.2.16 on 2026-08-16 18:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0006_alter_enrollment_usual_arrival_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unmarked', 'غير محدد'), ('present', 'حاضر'), ('absent', 'غائب')], default='unmarked', max_length=20)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('arrival_method', models.CharField(blank=True, choices=[('school_bus', 'باص المدرسة'), ('guardian', 'ولي الأمر')], default='', max_length=20)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('departure_method', models.CharField(blank=True, choices=[('school_bus', 'باص المدرسة'), ('guardian', 'ولي الأمر')], default='', max_length=20)),
                ('absence_type', models.CharField(blank=True, choices=[('excused', 'بعذر'), ('unexcused', 'دون عذر')], default='', max_length=20)),
                ('absence_reason', models.TextField(blank=True, default='')),
                ('absence_reason_source', models.CharField(blank=True, choices=[('guardian', 'ولي الأمر'), ('school', 'إدارة المدرسة')], default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='students.enrollment')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='attendance.attendancesheet')),
            ],
            options={
                'db_table': 'attendance_record',
                'ordering': ['enrollment__student__first_name', 'enrollment__student__last_name'],
                'constraints': [models.UniqueConstraint(fields=('sheet', 'enrollment'), name='att_record_unique_sheet_enrollment')],
            },
        ),
    ]
